version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./data/db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./data/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
volumes:
  db:
